branches:
  only:
    - master
language: ruby
rvm:
  - 1.9.3
  - 1.9.2
before_install:
  - sudo apt-get install python-swiftclient
install:
  - pip install --use-mirrors python-swiftclient
script:
  - bundle exec rake install
  - bundle exec rake generate
after_script:
  - cd public; swift -A $OS_AUTH_URL -U $OS_USERNAME -K $OS_PASSWORD upload myblog * ; cd ..
env:
  global:
  - OS_AUTH_URL=https://lon.identity.api.rackspacecloud.com/v1.0 
