---
branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
- 1.9.2
install:
- pip install python-swiftclient --use-mirrors --install-option="--user"
script:
- bundle exec rake install
- bundle exec rake generate
after_script:
- cd public; /home/travis/.local/bin/swift -A $OS_AUTH_URL -U $OS_USERNAME -K $OS_PASSWORD upload myblog *
  ; cd ..
env:
  global:
  - OS_AUTH_URL=https://lon.identity.api.rackspacecloud.com/v1.0
  - secure: ! '2Jr8i32d7q1/etoFvksiUvHSyfEdU3MRzDoyrIoqGHMI6GccT88bj9vJnS3Q

      Rt9ltsCw+3ZzWd4K9gRHg2aAc24GCUH2GEq0z7LrVD+zY6K1VpxTI/DFKZHq

      w3E2uc/94wSE2fL/sR1xNIMp5M/PJqaZIfiw2GU13wL4yYImrpg='
  - secure: ! '1fKQtRY0+OMvt7vroney/svLOaph6fg8qs764bgxvbvAox4Jr0PZbGvj2Hoa

      rc5Ktgo/mESMI1HImQDz44WkFb4oOpzy5IE8RY7H2LxZs/tOcweYw+yqwbMi

      qiMRoEFUGB+R8xL5H2gs4SQhhAZntlF7wARW5aom/pAnA+Ubr+o='
